---
label: Project
hide_body: true
display_field: title
fields:
- name: layout
  type: text
  config:
    required: false
  label: layout
  hidden: true
  default: default
- name: title
  type: text
  config:
    required: false
  label: Titulo
- name: autoria
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Autoria
- name: ficha_tecnica
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Ficha Técnica
- name: sinopse
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Sinopse
- name: main_image
  type: text
  config:
    required: false
  label: Imagem Principal
- name: imagens
  type: image_gallery
  config: {}
  label: Imagens
pages:
- _projects/7-poemas-para-um-mundo-novo.md
- _projects/concerto-para-uma-arvore.md
- _projects/do-principio-do-mundo.md
- _projects/instrumentaria-poetica.md
- _projects/passagem-secreta.md
