---
label: Project
hide_body: true
fields:
- name: layout
  type: text
  config:
    required: false
  label: layout
  hidden: true
  default: default
- name: title
  type: text
  config:
    required: false
  label: Titulo
- name: ficha_tecnica
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Ficha Técnica
- name: sinopse
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Sinopse
- name: main_image
  type: text
  config:
    required: false
  label: Imagem Principal
- name: imagens
  type: image_gallery
  config: {}
  label: Imagens
